# Generated by Django 4.2.13 on 2025-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=50),
            preserve_default=False,
        ),
    ]
