# Generated by Django 4.2.13 on 2025-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_employee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetconfig',
            name='company',
            field=models.CharField(default='Eligo'),
            preserve_default=False,
        ),
    ]
