# Generated by Django 4.2.13 on 2025-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_sheetconfig_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetconfig',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
