# Generated by Django 4.2.13 on 2025-07-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_sheetconfig_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Full Time', 'Full Time')], default='Full Time', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='Ps1', max_length=30),
        ),
    ]
