# Generated by Django 4.2.13 on 2025-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_employee_employee_type_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.CharField(default='Jay P', max_length=30),
        ),
    ]
