# Generated by Django 4.2.13 on 2025-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='applied_mail',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_leads',
            field=models.CharField(choices=[('assigned', 'assigned'), ('Not assigned', 'Not assigned')], default='Not assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Business Development Associate', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='selected_mail',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='signed_mail',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=10),
        ),
    ]
