# Generated by Django 4.2.13 on 2025-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_employee_applied_mail_employee_assigned_leads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='21981a05f2', max_length=100),
        ),
    ]
