# Generated by Django 4.2.13 on 2025-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('paid', 'not paid')], default='new', max_length=20),
        ),
    ]
