# Generated by Django 4.2.13 on 2025-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_lead_first_name_remove_lead_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='start_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
    ]
