# Generated by Django 4.2.13 on 2025-08-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_lead_start_month_alter_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_leads',
            field=models.CharField(choices=[('assigned', 'assigned'), ('not assigned', 'not assigned')], default='not assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='db.employee'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assignment_date',
            field=models.DateTimeField(blank=True, help_text='When lead was assigned to employee', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_probability',
            field=models.FloatField(blank=True, help_text='AI-predicted likelihood to convert (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_contact_date',
            field=models.DateTimeField(blank=True, help_text='When employee first contacted the lead', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup',
            field=models.DateTimeField(blank=True, help_text='Last follow-up attempt', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='For future priority-based assignment', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=50, help_text='Calculated score based on profile completeness'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=20),
        ),
    ]
