# Generated by Django 4.2.13 on 2025-08-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_lead_assigned_leads_lead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_load',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
