# Generated by Django 4.2.13 on 2025-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_employee_current_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_load',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
