# Generated by Django 4.2.13 on 2025-08-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_employee_current_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_load',
        ),
    ]
