# Generated by Django 4.2.13 on 2025-08-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_remove_employee_current_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('initiated', 'Initiated'), ('answered', 'Answered'), ('no_answer', 'No Answer'), ('failed', 'Failed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.lead')),
            ],
            options={
                'ordering': ['-call_time'],
            },
        ),
    ]
