# Generated by Django 4.2.13 on 2025-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_calllog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='call_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='outcome',
        ),
        migrations.AddField(
            model_name='calllog',
            name='action',
            field=models.CharField(default='nothing', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
