# Generated by Django 4.2.13 on 2025-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_calllog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='calllog',
            name='action',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('note_added', 'Note Added')], max_length=20),
        ),
    ]
